# Generated by Django 5.2.13 on 2026-04-16 18:46

import ckeditor.fields
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Kategori Adı')),
                ('name_tr', models.CharField(max_length=160, null=True, verbose_name='Kategori Adı')),
                ('name_en', models.CharField(max_length=160, null=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text="Örn: 'heart-pulse', 'stethoscope'", max_length=80, verbose_name='Lucide Icon Adı')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Uzmanlık Kategorisi',
                'verbose_name_plural': 'Uzmanlık Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=80, verbose_name='Lucide Icon')),
                ('short_description', models.CharField(help_text='Maksimum ~240 karakter — kart için.', max_length=240, verbose_name='Kısa Açıklama')),
                ('short_description_tr', models.CharField(help_text='Maksimum ~240 karakter — kart için.', max_length=240, null=True, verbose_name='Kısa Açıklama')),
                ('short_description_en', models.CharField(help_text='Maksimum ~240 karakter — kart için.', max_length=240, null=True, verbose_name='Kısa Açıklama')),
                ('full_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Detaylı Açıklama')),
                ('full_description_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detaylı Açıklama')),
                ('full_description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detaylı Açıklama')),
                ('symptoms', ckeditor.fields.RichTextField(blank=True, verbose_name='Belirtiler')),
                ('symptoms_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Belirtiler')),
                ('symptoms_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Belirtiler')),
                ('treatment_approach', ckeditor.fields.RichTextField(blank=True, verbose_name='Tedavi Yaklaşımım')),
                ('treatment_approach_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tedavi Yaklaşımım')),
                ('treatment_approach_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tedavi Yaklaşımım')),
                ('recovery_info', ckeditor.fields.RichTextField(blank=True, verbose_name='İyileşme Süreci')),
                ('recovery_info_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='İyileşme Süreci')),
                ('recovery_info_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='İyileşme Süreci')),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kapak Görseli')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('bento_size', models.CharField(choices=[('1x1', '1x1 — Orta'), ('2x1', '2x1 — Geniş'), ('1x2', '1x2 — Uzun'), ('2x2', '2x2 — Büyük')], default='1x1', max_length=10, verbose_name='Bento Kart Boyutu')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Başlık')),
                ('meta_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Başlık')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Açıklama')),
                ('meta_description_tr', models.TextField(blank=True, null=True, verbose_name='Meta Açıklama')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='expertise.specialtycategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Uzmanlık Alanı',
                'verbose_name_plural': 'Uzmanlık Alanları',
                'ordering': ['order', 'title'],
            },
        ),
    ]
