# Generated by Django 5.2.13 on 2026-04-17 01:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtyarea',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Uzmanlık alanları liste kartı ve bu uzmanlık alanı detay sayfasının üst görseli. Ana sayfada öne çıkan kartlarda da kullanılır.', max_length=255, null=True, verbose_name='Kapak Görseli'),
        ),
    ]
