# Generated by Django 5.2.13 on 2026-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Başlık')),
                ('title_tr', models.TextField(null=True, verbose_name='Başlık')),
                ('title_en', models.TextField(null=True, verbose_name='Başlık')),
                ('authors', models.CharField(help_text='Örn: Takmaz O, Bastu E, Ozbasli E, Gundogan S, ...', max_length=500, verbose_name='Yazarlar')),
                ('journal', models.CharField(max_length=240, verbose_name='Dergi')),
                ('year', models.PositiveIntegerField(verbose_name='Yıl')),
                ('volume', models.CharField(blank=True, max_length=40, verbose_name='Cilt')),
                ('issue', models.CharField(blank=True, max_length=40, verbose_name='Sayı')),
                ('pages', models.CharField(blank=True, max_length=60, verbose_name='Sayfa Aralığı')),
                ('doi', models.CharField(blank=True, max_length=120, verbose_name='DOI')),
                ('pubmed_id', models.CharField(blank=True, max_length=40, verbose_name='PubMed ID')),
                ('pmc_id', models.CharField(blank=True, max_length=40, verbose_name='PMC ID')),
                ('citation_count', models.PositiveIntegerField(default=0, verbose_name='Atıf Sayısı')),
                ('abstract', models.TextField(blank=True, verbose_name='Özet')),
                ('abstract_tr', models.TextField(blank=True, null=True, verbose_name='Özet')),
                ('abstract_en', models.TextField(blank=True, null=True, verbose_name='Özet')),
                ('full_url', models.URLField(blank=True, verbose_name='Tam Metin URL')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Yayın',
                'verbose_name_plural': 'Yayınlar',
                'ordering': ['-year', '-citation_count', 'order'],
            },
        ),
    ]
