# Generated by Django 5.2.13 on 2026-04-16 18:46

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('subject', models.CharField(blank=True, max_length=160, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('kvkk_consent', models.BooleanField(default=False, verbose_name='KVKK Onayı')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arşivlendi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Op. Dr. Savaş Gündoğan', max_length=200, verbose_name='Tam Ad')),
                ('title_short', models.CharField(default='Op. Dr.', max_length=60, verbose_name='Kısa Ünvan')),
                ('title_short_tr', models.CharField(default='Op. Dr.', max_length=60, null=True, verbose_name='Kısa Ünvan')),
                ('title_short_en', models.CharField(default='Op. Dr.', max_length=60, null=True, verbose_name='Kısa Ünvan')),
                ('title_long', models.CharField(default='Kadın Hastalıkları ve Doğum Uzmanı', max_length=160, verbose_name='Uzun Ünvan')),
                ('title_long_tr', models.CharField(default='Kadın Hastalıkları ve Doğum Uzmanı', max_length=160, null=True, verbose_name='Uzun Ünvan')),
                ('title_long_en', models.CharField(default='Kadın Hastalıkları ve Doğum Uzmanı', max_length=160, null=True, verbose_name='Uzun Ünvan')),
                ('hero_headline', models.CharField(default='Minimal İnvaziv Jinekolojik Cerrahi ve Kadın Sağlığı', max_length=220, verbose_name='Hero Ana Başlık')),
                ('hero_headline_tr', models.CharField(default='Minimal İnvaziv Jinekolojik Cerrahi ve Kadın Sağlığı', max_length=220, null=True, verbose_name='Hero Ana Başlık')),
                ('hero_headline_en', models.CharField(default='Minimal İnvaziv Jinekolojik Cerrahi ve Kadın Sağlığı', max_length=220, null=True, verbose_name='Hero Ana Başlık')),
                ('hero_subheadline', models.CharField(default='Laparoskopi · Robotik Cerrahi · vNOTES · Endometriozis · Ürojinekoloji', max_length=260, verbose_name='Hero Alt Başlık')),
                ('hero_subheadline_tr', models.CharField(default='Laparoskopi · Robotik Cerrahi · vNOTES · Endometriozis · Ürojinekoloji', max_length=260, null=True, verbose_name='Hero Alt Başlık')),
                ('hero_subheadline_en', models.CharField(default='Laparoskopi · Robotik Cerrahi · vNOTES · Endometriozis · Ürojinekoloji', max_length=260, null=True, verbose_name='Hero Alt Başlık')),
                ('hero_intro_paragraph', models.TextField(blank=True, help_text='Hero bölümünde görünen kısa tanıtım paragrafı.', verbose_name='Hero Paragraf')),
                ('hero_intro_paragraph_tr', models.TextField(blank=True, help_text='Hero bölümünde görünen kısa tanıtım paragrafı.', null=True, verbose_name='Hero Paragraf')),
                ('hero_intro_paragraph_en', models.TextField(blank=True, help_text='Hero bölümünde görünen kısa tanıtım paragrafı.', null=True, verbose_name='Hero Paragraf')),
                ('portrait_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Portre Fotoğraf')),
                ('hero_background', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Hero Arka Plan')),
                ('signature_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='İmza Görseli')),
                ('bio_short', models.TextField(blank=True, help_text='Yaklaşık 150 kelime.', verbose_name='Kısa Biyografi')),
                ('bio_short_tr', models.TextField(blank=True, help_text='Yaklaşık 150 kelime.', null=True, verbose_name='Kısa Biyografi')),
                ('bio_short_en', models.TextField(blank=True, help_text='Yaklaşık 150 kelime.', null=True, verbose_name='Kısa Biyografi')),
                ('bio_long', ckeditor.fields.RichTextField(blank=True, verbose_name='Uzun Biyografi')),
                ('bio_long_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Uzun Biyografi')),
                ('bio_long_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Uzun Biyografi')),
                ('philosophy_quote', models.TextField(blank=True, verbose_name='Felsefe Alıntısı')),
                ('philosophy_quote_tr', models.TextField(blank=True, null=True, verbose_name='Felsefe Alıntısı')),
                ('philosophy_quote_en', models.TextField(blank=True, null=True, verbose_name='Felsefe Alıntısı')),
                ('email_public', models.EmailField(default='savas.gundogan@acibadem.com', max_length=254, verbose_name='Halka Açık E-posta')),
                ('phone_public', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('appointment_url', models.URLField(default='https://www.acibadem.com.tr/doktor/savas-gundogan/', verbose_name='Randevu URL')),
                ('hospital_name', models.CharField(default='Acıbadem Maslak Hastanesi', max_length=160, verbose_name='Hastane Adı')),
                ('hospital_name_tr', models.CharField(default='Acıbadem Maslak Hastanesi', max_length=160, null=True, verbose_name='Hastane Adı')),
                ('hospital_name_en', models.CharField(default='Acıbadem Maslak Hastanesi', max_length=160, null=True, verbose_name='Hastane Adı')),
                ('hospital_address', models.TextField(default='Büyükdere Cad. No:40, 34457 Maslak / İstanbul', verbose_name='Hastane Adresi')),
                ('hospital_address_tr', models.TextField(default='Büyükdere Cad. No:40, 34457 Maslak / İstanbul', null=True, verbose_name='Hastane Adresi')),
                ('hospital_address_en', models.TextField(default='Büyükdere Cad. No:40, 34457 Maslak / İstanbul', null=True, verbose_name='Hastane Adresi')),
                ('google_maps_embed_url', models.TextField(blank=True, verbose_name='Google Maps Embed URL')),
                ('instagram_url', models.URLField(default='https://www.instagram.com/dr.savasgundogan/', verbose_name='Instagram URL')),
                ('instagram_handle', models.CharField(default='@dr.savasgundogan', max_length=60, verbose_name='Instagram Kullanıcı Adı')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('google_scholar_url', models.URLField(default='https://scholar.google.com/citations?user=9hUh--8AAAAJ&hl=en', verbose_name='Google Scholar URL')),
                ('acibadem_profile_tr', models.URLField(default='https://www.acibadem.com.tr/doktor/savas-gundogan/', verbose_name='Acıbadem Profil (TR)')),
                ('acibadem_profile_en', models.URLField(default='https://www.acibadem.com.tr/en/doctor/savas-gundogan/', verbose_name='Acıbadem Profil (EN)')),
                ('years_of_experience', models.PositiveIntegerField(default=12, verbose_name='Yıllık Deneyim')),
                ('publication_count', models.PositiveIntegerField(default=20, verbose_name='Yayın Sayısı')),
                ('procedures_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prosedür Sayısı')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doktor Profili',
                'verbose_name_plural': 'Doktor Profili',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Op. Dr. Savaş Gündoğan', max_length=120, verbose_name='Site Adı')),
                ('default_meta_title', models.CharField(blank=True, max_length=200, verbose_name='Varsayılan Meta Başlık')),
                ('default_meta_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Varsayılan Meta Başlık')),
                ('default_meta_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Varsayılan Meta Başlık')),
                ('default_meta_description', models.TextField(blank=True, verbose_name='Varsayılan Meta Açıklama')),
                ('default_meta_description_tr', models.TextField(blank=True, null=True, verbose_name='Varsayılan Meta Açıklama')),
                ('default_meta_description_en', models.TextField(blank=True, null=True, verbose_name='Varsayılan Meta Açıklama')),
                ('default_og_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Varsayılan OG Görseli')),
                ('cookie_banner_text', models.TextField(default="Sitemizde deneyiminizi iyileştirmek için çerezler kullanılmaktadır. Detaylar için Aydınlatma Metni'ni inceleyebilirsiniz.", verbose_name='Çerez Banner Metni')),
                ('cookie_banner_text_tr', models.TextField(default="Sitemizde deneyiminizi iyileştirmek için çerezler kullanılmaktadır. Detaylar için Aydınlatma Metni'ni inceleyebilirsiniz.", null=True, verbose_name='Çerez Banner Metni')),
                ('cookie_banner_text_en', models.TextField(default="Sitemizde deneyiminizi iyileştirmek için çerezler kullanılmaktadır. Detaylar için Aydınlatma Metni'ni inceleyebilirsiniz.", null=True, verbose_name='Çerez Banner Metni')),
                ('kvkk_body', ckeditor.fields.RichTextField(blank=True, verbose_name='Aydınlatma Metni İçeriği')),
                ('kvkk_body_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Aydınlatma Metni İçeriği')),
                ('kvkk_body_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Aydınlatma Metni İçeriği')),
                ('privacy_body', ckeditor.fields.RichTextField(blank=True, verbose_name='Gizlilik Politikası İçeriği')),
                ('privacy_body_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Gizlilik Politikası İçeriği')),
                ('privacy_body_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Gizlilik Politikası İçeriği')),
                ('newsletter_enabled', models.BooleanField(default=False, verbose_name='Bülten Aktif')),
                ('google_analytics_id', models.CharField(blank=True, max_length=40, verbose_name='Google Analytics ID')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Bakım Modu')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
