# Generated by Django 5.2.13 on 2026-04-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='Yol')),
                ('language', models.CharField(blank=True, max_length=8, verbose_name='Dil')),
                ('referrer', models.TextField(blank=True, verbose_name='Referans')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='User-Agent')),
                ('visitor_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Ziyaretçi Parmak İzi')),
                ('device_type', models.CharField(choices=[('desktop', 'Masaüstü'), ('mobile', 'Mobil'), ('tablet', 'Tablet'), ('bot', 'Bot')], default='desktop', max_length=10, verbose_name='Cihaz')),
                ('is_bot', models.BooleanField(db_index=True, default=False, verbose_name='Bot mu?')),
                ('country', models.CharField(blank=True, max_length=4, verbose_name='Ülke')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zaman')),
            ],
            options={
                'verbose_name': 'Sayfa Görüntüleme',
                'verbose_name_plural': 'Sayfa Görüntülemeleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_pagevi_created_4d45f9_idx'), models.Index(fields=['path', '-created_at'], name='core_pagevi_path_d3295b_idx'), models.Index(fields=['is_bot', '-created_at'], name='core_pagevi_is_bot_484fb2_idx')],
            },
        ),
    ]
