# Generated by Django 5.2.13 on 2026-04-17 01:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Tarayıcı sekmesi ikonu (kare, tercihen 512x512 PNG).', max_length=255, null=True, verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Header için logo. Boşsa 'SG' gradient rozeti gösterilir.", max_length=255, null=True, verbose_name='Site Logosu (Açık Zemin)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo_light',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Footer/koyu arka plan için açık renkli logo.', max_length=255, null=True, verbose_name='Site Logosu (Koyu Zemin)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_icon_facebook',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Facebook İkonu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_icon_instagram',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Instagram İkonu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_icon_linkedin',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='LinkedIn İkonu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_icon_scholar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Google Scholar İkonu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_icon_youtube',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='YouTube İkonu'),
        ),
    ]
