# Generated by Django 5.2.13 on 2026-04-17 01:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_favicon_sitesettings_site_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='hero_background',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Ana sayfanın en üstündeki büyük hero bölümünün arka plan görseli.', max_length=255, null=True, verbose_name='Hero Arka Plan'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='portrait_photo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Ana sayfa kısa biyografi bölümü, Hakkımda hero, Blog yazar kartı.', max_length=255, null=True, verbose_name='Portre Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='signature_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Hakkımda sayfası alt bölüm imza alanı (opsiyonel).', max_length=255, null=True, verbose_name='İmza Görseli'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_og_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Sosyal medyada (Facebook, WhatsApp, LinkedIn) paylaşıldığında çıkan önizleme görseli.', max_length=255, null=True, verbose_name='Varsayılan OG Görseli'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Tarayıcı sekmesi ikonu (kare, tercihen 512x512 PNG).', max_length=255, null=True, verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Sitede görünür: Header (üst menü) logosu. Boşsa 'SG' gradient rozeti gösterilir.", max_length=255, null=True, verbose_name='Site Logosu (Açık Zemin)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo_light',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Footer (alt bölüm, koyu arka plan) logosu. Açık renkli bir versiyon yükleyin.', max_length=255, null=True, verbose_name='Site Logosu (Koyu Zemin)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_icon_facebook',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Footer Facebook linkinin yanındaki ikon (Facebook URL girildiğinde).', max_length=255, null=True, verbose_name='Facebook İkonu'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_icon_instagram',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Header, footer ve mobil menüde Instagram linkinin yanındaki ikon.', max_length=255, null=True, verbose_name='Instagram İkonu'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_icon_linkedin',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Footer LinkedIn linkinin yanındaki ikon (LinkedIn URL girildiğinde).', max_length=255, null=True, verbose_name='LinkedIn İkonu'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_icon_scholar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Footer ve mobil menüde Google Scholar linkinin yanındaki ikon.', max_length=255, null=True, verbose_name='Google Scholar İkonu'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_icon_youtube',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Footer YouTube linkinin yanındaki ikon (YouTube URL girildiğinde).', max_length=255, null=True, verbose_name='YouTube İkonu'),
        ),
    ]
