# Generated by Django 5.2.13 on 2026-04-16 18:46

import ckeditor.fields
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expertise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Kategori Adı')),
                ('name_tr', models.CharField(max_length=160, null=True, verbose_name='Kategori Adı')),
                ('name_en', models.CharField(max_length=160, null=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Blog Kategorisi',
                'verbose_name_plural': 'Blog Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Başlık')),
                ('title_tr', models.CharField(max_length=220, null=True, verbose_name='Başlık')),
                ('title_en', models.CharField(max_length=220, null=True, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, max_length=320, verbose_name='Özet')),
                ('excerpt_tr', models.TextField(blank=True, max_length=320, null=True, verbose_name='Özet')),
                ('excerpt_en', models.TextField(blank=True, max_length=320, null=True, verbose_name='Özet')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('content_tr', ckeditor.fields.RichTextField(null=True, verbose_name='İçerik')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='İçerik')),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kapak Görseli')),
                ('author_name', models.CharField(default='Op. Dr. Savaş Gündoğan', max_length=160, verbose_name='Yazar')),
                ('read_time_minutes', models.PositiveIntegerField(default=5, verbose_name='Okuma Süresi (dk)')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayında'), ('archived', 'Arşiv')], default='draft', max_length=16, verbose_name='Durum')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Başlık')),
                ('meta_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Başlık')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Açıklama')),
                ('meta_description_tr', models.TextField(blank=True, null=True, verbose_name='Meta Açıklama')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='Kategori')),
                ('related_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='expertise.specialtyarea', verbose_name='İlgili Uzmanlık Alanı')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
