# Generated by Django 5.2.13 on 2026-04-17 01:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Blog liste kartı, blog detay sayfası üst görseli ve sosyal medya paylaşım önizlemesi.', max_length=255, null=True, verbose_name='Kapak Görseli'),
        ),
    ]
