# Generated by Django 5.2.13 on 2026-04-16 18:46

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expertise', '0001_initial'),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Kategori Adı')),
                ('name_tr', models.CharField(max_length=160, null=True, verbose_name='Kategori Adı')),
                ('name_en', models.CharField(max_length=160, null=True, verbose_name='Kategori Adı')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'SSS Kategorisi',
                'verbose_name_plural': 'SSS Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Soru')),
                ('question_tr', models.CharField(max_length=300, null=True, verbose_name='Soru')),
                ('question_en', models.CharField(max_length=300, null=True, verbose_name='Soru')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Cevap')),
                ('answer_tr', ckeditor.fields.RichTextField(null=True, verbose_name='Cevap')),
                ('answer_en', ckeditor.fields.RichTextField(null=True, verbose_name='Cevap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='faq.faqcategory', verbose_name='Kategori')),
                ('related_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_items', to='expertise.specialtyarea', verbose_name='İlgili Uzmanlık')),
                ('related_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_items', to='media_library.video', verbose_name='İlgili Video')),
            ],
            options={
                'verbose_name': 'SSS',
                'verbose_name_plural': 'Sıkça Sorulan Sorular',
                'ordering': ['order', 'id'],
            },
        ),
    ]
