# Generated by Django 5.2.13 on 2026-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Kurum')),
                ('institution_tr', models.CharField(max_length=200, null=True, verbose_name='Kurum')),
                ('institution_en', models.CharField(max_length=200, null=True, verbose_name='Kurum')),
                ('degree', models.CharField(max_length=160, verbose_name='Derece')),
                ('degree_tr', models.CharField(max_length=160, null=True, verbose_name='Derece')),
                ('degree_en', models.CharField(max_length=160, null=True, verbose_name='Derece')),
                ('field', models.CharField(blank=True, max_length=160, verbose_name='Alan')),
                ('field_tr', models.CharField(blank=True, max_length=160, null=True, verbose_name='Alan')),
                ('field_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Alan')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='Konum')),
                ('location_tr', models.CharField(blank=True, max_length=160, null=True, verbose_name='Konum')),
                ('location_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Konum')),
                ('year_start', models.PositiveIntegerField(verbose_name='Başlangıç Yılı')),
                ('year_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bitiş Yılı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_highlight', models.BooleanField(default=False, verbose_name='Ana Sayfa Öne Çıkan')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitim',
                'ordering': ['-year_start', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Pozisyon')),
                ('position_tr', models.CharField(max_length=200, null=True, verbose_name='Pozisyon')),
                ('position_en', models.CharField(max_length=200, null=True, verbose_name='Pozisyon')),
                ('institution', models.CharField(max_length=200, verbose_name='Kurum')),
                ('institution_tr', models.CharField(max_length=200, null=True, verbose_name='Kurum')),
                ('institution_en', models.CharField(max_length=200, null=True, verbose_name='Kurum')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='Konum')),
                ('location_tr', models.CharField(blank=True, max_length=160, null=True, verbose_name='Konum')),
                ('location_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Konum')),
                ('year_start', models.PositiveIntegerField(verbose_name='Başlangıç Yılı')),
                ('year_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bitiş Yılı')),
                ('is_current', models.BooleanField(default=False, verbose_name='Devam Ediyor')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_highlight', models.BooleanField(default=False, verbose_name='Ana Sayfa Öne Çıkan')),
            ],
            options={
                'verbose_name': 'Deneyim',
                'verbose_name_plural': 'Deneyim',
                'ordering': ['-year_start', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dernek / Kuruluş Adı')),
                ('name_tr', models.CharField(max_length=200, null=True, verbose_name='Dernek / Kuruluş Adı')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Dernek / Kuruluş Adı')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('year_joined', models.PositiveIntegerField(blank=True, null=True, verbose_name='Katılım Yılı')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Üyelik',
                'verbose_name_plural': 'Üyelikler',
                'ordering': ['order', 'name'],
            },
        ),
    ]
