# Generated by Django 5.2.13 on 2026-04-16 18:46

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('name_tr', models.CharField(max_length=120, null=True, verbose_name='Kategori Adı')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Video Kategorisi',
                'verbose_name_plural': 'Video Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Başlık')),
                ('title_tr', models.CharField(max_length=220, null=True, verbose_name='Başlık')),
                ('title_en', models.CharField(max_length=220, null=True, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram Reel'), ('youtube', 'YouTube'), ('youtube_short', 'YouTube Short'), ('acibadem', 'Acıbadem Resmi')], default='instagram', max_length=20, verbose_name='Platform')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('embed_code', models.TextField(blank=True, help_text="Varsa buraya iframe HTML'i yapıştırın.", verbose_name='Özel Embed Kodu')),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kapak Görseli')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_official_acibadem', models.BooleanField(default=False, verbose_name='Acıbadem Resmi Hesabında Yayınlandı')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('view_count_manual', models.PositiveIntegerField(blank=True, default=0, verbose_name='İzlenme Sayısı (manuel)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='media_library.videocategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
                'ordering': ['-is_featured', 'order', '-publish_date'],
            },
        ),
    ]
