# Generated by Django 5.2.13 on 2026-04-17 01:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sitede görünür: Videolar sayfasındaki video kartı küçük resmi (thumbnail). Ana sayfa video bölümünde öne çıkanlarda da kullanılır.', max_length=255, null=True, verbose_name='Kapak Görseli'),
        ),
    ]
